#!/bin/bash

#gather data from report
myuser=$USER
myhostname=$HOSTNAME
myip=$(ip a | grep -w  inet | awk '{print$2}')

echo "
System Report generated by $myuser, DATE/TIME

System Information
------------------
Hostname: $myhostname
"
