#!/bin/bash

#gather data from report
myuser=$USER
sysdate=$(date +%F)
systime=$(date | awk '{print $5,$6}')
myhostname=$HOSTNAME
myip=$(ip a | grep -w  inet | awk '{print$2}')
osinfo=$(hostnamectl | grep -w Operating | awk '{print $3,$4,$5}')
#hostnamectl | grep -w Kernel | awk '{print $2,$3}')
uptime=$(w | grep -w up | awk {'print $3,substr($4,1, length($4)-1)'})


echo "
System Report generated by $myuser, $sysdate/$systime

System Information
------------------
Hostname: $myhostname
Os: $osinfo
Uptime: $uptime
"
